"""Create TaskStatus enum and alter Task table

Revision ID: a263cbda0236
Revises: 0123456789ab
Create Date: 2026-01-20 19:25:28.830442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'a263cbda0236'
down_revision = '0123456789ab'
branch_labels = None
depends_on = None

# Why: Define the ENUM type explicitly for reuse in upgrade and downgrade.
# 'create_type=False' gives us manual control over its lifecycle.
task_status_enum = postgresql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='taskstatus', create_type=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Why: Create the ENUM type in the database before it is used.
    task_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Why: Alter the column to use the new ENUM type.
    # 'postgresql_using' is crucial for telling PostgreSQL how to cast
    # the existing VARCHAR data to the new 'taskstatus' ENUM type.
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(),
               type_=task_status_enum,
               existing_nullable=False,
               postgresql_using='status::text::taskstatus')
               
    # Why: Enforce the model's constraint that a task must have an owner.
    op.alter_column('task', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
               
    # Why: Improve query performance for filtering tasks by title.
    op.create_index(op.f('ix_task_title'), 'task', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_title'), table_name='task')
    
    op.alter_column('task', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
               
    # Why: Revert the column back to a plain VARCHAR.
    op.alter_column('task', 'status',
               existing_type=task_status_enum,
               type_=sa.VARCHAR(),
               existing_nullable=False)
               
    # Why: Remove the ENUM type from the database after it's no longer in use.
    task_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
